server:
    port: ${PORT:8080}
spring:
    datasource:
        driver-class-name: oracle.jdbc.driver.OracleDriver
        url: ${DATA_BASE_LOYALTY_URL:jdbc:oracle:thin:@localhost:1521/xe}
        username: ${DATA_BASE_LOYALTY_USER:APPLOYCLIENTQA2}
        password: ${DATA_BASE_LOYALTY_PASS:geocom}    
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: none
eureka:
    client: 
        service-url: 
            defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
        register-with-eureka: false
gu-entities:
    PhoneType:
        cell: CELL    
        catogory: PRIMARY
ms-messager:
    messager:
        200: Accept
        201: Ya existe una cuenta creada con esa tarjeta
        204: Tarjeta ya existente
        400: Datos invalidos
        401: No existe la tarjeta
        402: No existe cliente asociado a la tarjeta
        403: Error tarjeta asociada a varios clientes
        404: Cliente no posee un celular asociado
        405: No existen clientes para los datos proporcionados
        406: Direccion de Email invalida
        407: No se puede validar la tarjeta en este momento
        408: Codigo incorrecto  
        409: El codigo sms ya expiro
        410: La tarjeta no se ha validado
        411: No se puede crear cuenta porque el Email ya existe en otro Cliente
        412: Ya tienes una cuenta creada con ese Email, ve al login para ingresar
        413: No se puede dar de alta Email si no valido la tarjeta

        700: La tarjeta esta asociada a un cliente no habilidato
        701: El cliente no ha validado el Email

        800: Existe el usuario
        801: No existe el usuario
        802: Error existe varios usuarios con el mismo Email

        501: Error interno de autenticacion
        502: Ya existe un usuario con ese email
card:
    sms:
        time:
            expiration: 120    
        digit: 4
ms:
    keycloack-adapter:
        url: http://localhost:8008