server:
    port: ${PORT:8080}

spring:
    security:
        oauth2:
            client:
                registration:
                    keycloack:
                        authorization-grant-type: client_credentials
                        client-id:
                            ${CLIENT_ID:admin-cli}
                        client-secret:
                            ${CLIENT_SECRECT:NTfmkc2Az1Uzp7GRN1drH28fkDoYOnQy}
                provider:
                    keycloack:
                        token-uri:
                            ${URL_ACCESS:http://host.docker.internal:8181/auth/realms/Master/protocol/openid-connect/token}
keycloack:
    uri_base:
        ${URL_BASE_CLI:http://host.docker.internal:8181/auth/admin/realms/YZA}                        
    path-users:
        ${URL_USERS_CLI:/users}                        
eureka:
    client: 
        service-url: 
            defaultZone: ${EUREKA_SERVER:http://ms-register-eureka:8080/eureka}
        register-with-eureka: true
    instance:
        hostname: localhost
ms-messager:
    messager:
        200: Accept
        201: Ya existe una cuenta creada con esa tarjeta
        204: Tarjeta ya existente
        400: Datos invalidos
        401: No existe la tarjeta
        402: No existe cliente asociado a la tarjeta
        403: Error tarjeta asociada a varios clientes
        404: Cliente no posee un celular asociado
        405: No existen clientes para los datos proporcionados
        406: Direccion de Email invalida
        407: No se puede validar la tarjeta en este momento
        408: Codigo incorrecto  
        409: El codigo sms ya expiro
        410: La tarjeta no se ha validado
        411: No se puede crear cuenta porque el Email ya existe en otro Cliente
        412: Ya tienes una cuenta creada con ese Email, ve al login para ingresar
        413: No se puede dar de alta Email si no valido la tarjeta

        800: Existe el usuario
        801: No existe el usuario
        802: Error existe varios usuarios con el mismo Email

        501: Error interno de autenticacion
        502: Ya existe un usuario con ese email
